VENDOR=Spirent
NAME=vstc
IMAGE_FORMAT=qcow2
IMAGE_GLOB=*.qcow2

VERSION=$(shell echo $(IMAGE) | sed -e 's/spirent_vstc-\(.*\)\.qcow2/\1/')

-include ../makefile-sanity.include
-include ../makefile.include
